from seeder.models import ColumnInfo, ForeignKeyInfo, Schema, TableInfo

EMPLOYMENT_TABLES: Schema = [
    TableInfo(
        name="Firma",
        columns=[
            ColumnInfo(
                name="id_firma",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="nazwa",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="regon",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="nip",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="id_adres",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="Adres", referenced_column="id_adres"
                ),
            ),
        ],
    ),
    TableInfo(
        name="RodzajUmowy",
        columns=[
            ColumnInfo(
                name="id_rodzaj_umowy",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="nazwa",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
        ],
    ),
    TableInfo(
        name="Zatrudnienie",
        columns=[
            ColumnInfo(
                name="id_zatrudnienie",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="id_osoba",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="Osoba", referenced_column="id_osoba"
                ),
            ),
            ColumnInfo(
                name="id_firma",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="Firma", referenced_column="id_firma"
                ),
            ),
            ColumnInfo(
                name="wynagrodzenie",
                data_type="REAL",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="data_zatrudnienia",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="data_zwolnienia",
                data_type="TEXT",
                is_nullable=True,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="stanowisko",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="id_rodzaj_umowy",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="RodzajUmowy",
                    referenced_column="id_rodzaj_umowy",
                ),
            ),
        ],
    ),
]
