from seeder.models import ColumnInfo, ForeignKeyInfo, Schema, TableInfo

GEOGRAPHY_TABLES: Schema = [
    TableInfo(
        name="Wojewodztwo",
        columns=[
            ColumnInfo(
                name="id_wojewodztwo",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="nazwa",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
        ],
    ),
    TableInfo(
        name="Powiat",
        columns=[
            ColumnInfo(
                name="id_powiat",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="nazwa",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="id_wojewodztwo",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="Wojewodztwo", referenced_column="id_wojewodztwo"
                ),
            ),
        ],
    ),
    TableInfo(
        name="Gmina",
        columns=[
            ColumnInfo(
                name="id_gmina",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="nazwa",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="id_powiat",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="Powiat", referenced_column="id_powiat"
                ),
            ),
        ],
    ),
    TableInfo(
        name="Miejscowosc",
        columns=[
            ColumnInfo(
                name="id_miejscowosc",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=True,
                is_auto_increment=True,
            ),
            ColumnInfo(
                name="nazwa",
                data_type="TEXT",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
            ),
            ColumnInfo(
                name="id_gmina",
                data_type="INTEGER",
                is_nullable=False,
                is_primary_key=False,
                is_auto_increment=False,
                foreign_key=ForeignKeyInfo(
                    referenced_table="Gmina",
                    referenced_column="id_gmina",
                ),
            ),
        ],
    ),
]
