[Firma]
rows = 25
fields = ["nazwa", "regon", "nip"]

[Firma.columns.nazwa]
generator = "nazwa_firmy"

[Firma.columns.nip]
generator = "nip"

[Firma.columns.regon]
generator = "regon"

[Osoba]
rows = 150
fields = ["imie", "nazwisko", "data_urodzenia", "pesel", "plec"]

[Osoba.columns.imie]
generator = "imie"

[Osoba.columns.nazwisko]
generator = "nazwisko"

[Osoba.columns.data_urodzenia]
generator = "data_urodzenia"

[Osoba.columns.pesel]
generator = "pesel"

[Osoba.columns.plec]
generator = "plec"